v1.5.2

diff --git a/stow/stow-all-files b/stow/stow-all-files
--- a/stow/stow-all-files
+++ b/stow/stow-all-files
@@ -25,7 +25,8 @@ BLUE=$(tput setaf 6)
 RED=$(tput setaf 1)
 NC=$(tput sgr 0)
 WIDTH=$(tput cols)
-
+GREEN=$(tput setaf 46)
+readonly config_file=stow.list
 
 
 function usage()
@@ -34,13 +35,16 @@ function usage()
 line_fill;
 cat <<EOF
 Usage: ${YELLOW}${SCRIPT}${NC} [options]
-[-s --stow ]           [Stows all the files in directory]
-[-v --version]         [Display version info]
-[-h --help]            [Display this help message]
-This script's metadata Generated by ${gen_source} on ${gen_date}.
-This script uses a config file 'stow.list' containing list of directories to be stowed.
-If the Dotfiles directory has been changed then you have to delete symlinks manually.
-If you want to stow other directories then just add them to the file with one directory per line.
+[-s --stow ]       [Stows all the files in directory]
+[-v --version]     [Display version info]
+[-g]               [Try stowing files without config (NOT RECOMMENDED) ]
+[-h --help]        [Display this help message]
+
+* Metadata Generated by ${gen_source} on ${gen_date}.
+
+* This script uses a config file ${YELLOW} "${config_file}"${NC} containing \
+list of directories to be stowed. If the Dotfiles directory has been changed \
+then you have to delete symlinks manually.
 
 Notice any bugs? Please report it.
 You are welcome to create a pull request on Github, if you can make it better in any way!
@@ -67,7 +71,14 @@ function display_version()
 {
   line_fill "${BLUE}";
   printf "${spacing_string} ${YELLOW} ${SCRIPT} ${NC}\n${spacing_string} ${YELLOW} ${gen_date} ${NC}\n" "Executable:" "Generated on:";
+  printf "Following directories are listed in config file.\n"
   line_fill "${BLUE}";
+  if [ -f ~/.bash_aliases ]; then
+      cat stow.list
+    else
+      printf "Config file:${config_file} not found!"
+  fi
+  line_fill;
 }
 
 function stow_files()
@@ -161,6 +172,9 @@ function main()
       # Process command line arguments.
       while [ "$1" != "" ]; do
           case ${1} in
+              -g)                     stow_files;
+                                      exit $?;
+                                      ;;
               -s | --stow )           stow_files_withconfig;
                                       exit $?;
                                       ;;
