bugfixes and improved stow scripts, +office tools

diff --git a/android-tools/adb-screenshot b/android-tools/adb-screenshot
--- a/android-tools/adb-screenshot
+++ b/android-tools/adb-screenshot
@@ -1,71 +1,171 @@
 #!/usr/bin/env bash
-SCRIPT=ADB-Screenshot
-printf "\n$(tput setaf 3)Hello! \nI am "$SCRIPT"!\n \n$(tput setaf 6)Running on $(uname -n) as $USER $(tput sgr 0)\n"
-#define default Dirctory
-SCREENSHOT_PATH=$HOME/Phone/Screenshots/adb-screenshot-script-outputs
-mkdir -p  $SCREENSHOT_PATH
-OVRRIDE_RATE_FLAG=false
-#default interval
+
+# This is a bash utility to help take screenshots on your Android device vua adb.
+# Version:2.4
+# Author: Prasad Tengse
+# Licence: GPLv3
+# Github Repository: https://github.com/tprasadtp/<repo-name>
+# Requirements - Bash v4.4 and above
+#              - Android Jellybean and above.
+#              - latest version of adb and fastboot installed properly and are in your $PATH.
+#              - udev rules are properly set for your device/manufacturer.
+#              - ADB debugging enabled and your pc is trusted. (duh!)
+#              - Assumes that only one adb device is connected to the PC. Which holds true most of the time.
+#                Its okay if you have multiple devices connected (including emulators),
+#                but dont enable adb on multiple devicees.
+#              - Windows Subsystem for Linux is untested and un-verified.
+#              - Have common sense.
+#
+#COLORS and Data for Printf
+ORANGE=$(tput setaf 9)
+YELLOW=$(tput setaf 3)
+DEEP_BLUE=$(tput setaf 4)
+BLUE=$(tput setaf 6)
+RED=$(tput setaf 1)
+GREEN=$(tput setaf 46)
+PINK2=$(tput setaf 9)
+NC=$(tput sgr 0)
+WIDTH=$(tput cols)
+
+DATE=`date +%Y-%m-%d:%H:%M:%S`
+readonly SCRIPT=`basename "$0"`
+readonly VERSION="2.0"
+SCREENSHOT_PATH=$HOME/Phone/Screenshots/screenshot-adb-outputs
+OVRRIDE_RATE_FLAG= false
 interval_time=5
+COUNT_LIMIT_FLAG= false
 
-while [ "$1" != "" ]; do
-    case $1 in
-        -t | --time )           shift
-                                interval_time=$1
-                                ;;
-        -o | --output )         shift
-                                SCREENSHOT_PATH=$1
-                                ;;
-        -c | --count )          shift
-                                COUNT_LIMIT_FLAG='true';
-                                COUNT_LIMIT="$1"
-                                ;;
-        * )                     usage
-                                exit 1
-    esac
-    shift
-done
+function line_fill()
+{
+  # Function simply draws a line accross width of the terminal for a given color
+  # Input: Variable defining color in format $(tput setaf <number)
+  # If input argument is empty it reverts to a default color of Yellow.
+  if [ $# -eq 0 ]; then
+    local fill_color=${YELLOW}
+  else
+    local fill_color=${1}
+  fi
+  printf "${fill_color}%-${WIDTH}s@%s${NC}\n" | sed -e 's/ /-/g' -e 's/-@/ /' -e 's/@-/ /'
+}
 
 
+function display_version()
+{
+  line_fill "${BLUE}"
+  printf "%+11s ${YELLOW} ${SCRIPT} ${NC}\n%+11s ${YELLOW} ${VERSION} ${NC}\n" "Executable:" "Version:";
+  line_fill "${BLUE}"
+}
+
+
+function device_init()
+{
+  #Function that waits for adb and shouts what is connected
+  #Input:None Output:Device details if connected
+  printf "\n${BLUE}Waiting for Device...${NC}"
+	adb wait-for-device
+	DEVICE_NAME=$(adb shell getprop ro.product.model)
+	DEVICE_SERIAL=$(adb shell getprop ro.serialno)
+	printf "\n${DEVICE_NAME}:${DEVICE_SERIAL} is Connected!\n"
+  line_fill;
+}
+
+
+function screenshot_stream()
+{
+  # function to take screenshots regular interval-value-in-seconds
+  # Default interval_time is 5 sec, Default Path is
+  # $HOME/Phone/Screenshots/adb-screenshot-script-outputs
+  mkdir -p  ${SCREENSHOT_PATH}
+  #
+  printf "\n${YELLOW}Capturing screenshots approximately every ${interval_time} seconds on your device.\n"
+  line_fill;
+  #Wait for adb device
+  device_init
+
+  printf  "\n${YELLOW}Press CTRL+C to stop....${NC}\n"
+  count=1
+  printf "${BLUE}Screenshots are save under :${FILE_PATH}\n"
+  while true
+  do
+  {
+      #Date stamp
+      DATE=`date +%Y-%m-%d:%H:%M:%S`
+      FILE_PATH=${SCREENSHOT_PATH}
+      FILE_NAME=${DEVICE_NAME}-${DATE}-${count}.png
+      adb exec-out screencap -p > "$FILE_PATH/$FILE_NAME";
+      printf "\nCaptured Screenshot ${count} as: ${FILE_NAME}\n";
+      #sleep $1
+      if ${COUNT_LIMIT_FLAG}; then
+          {
+              if [[ $count -eq $COUNT_LIMIT ]]; then
+                  printf "\n$(tput setaf 6)Saved total of ${count} Screenshots in "${FILE_PATH}".$(tput sgr 0)\n";
+                  exit 0;
+              fi;
+          }
+      fi
+      count=$((count+1));
+      sleep ${interval_time};
+  }
+  done
+
+}
 usage()
 {
-    printf "Usage: %s: [-t interval-value-in-seconds] [-o absolute-output-path] [-c number-of-screenshots -f <to overrride interval limits>] \n"
+#Prints out help menu
+line_fill;
+cat <<EOF
+Usage: ${YELLOW}${SCRIPT}${NC} [options]
+[-t --time <int> ]      [Time interval between screenshots]
+[-o --output <path> ]   [Output path (absolute)]
+[-c --count <int> ]     [Number of screenshots to be taken]
+[-h --help]             [Display this help message]
+[-v --version]          [Display version info]
+Running without any arguments will use following default values.
+* time interval between screenshots = 5 seconds
+* Path to Captured screenshots: S$HOME/Phone/Screenshots/screenshot-adb-outputs
+* Press Ctrl+C to stop the script.
+Notice any bugs? Please report it.
+You are welcome to create a pull request on Github, if you can make it better in any way!
+${BLUE}https://github.com/tprasadtp/minchu${NC}
+EOF
+line_fill;
 }
 
-printf "\n$(tput setaf 3)Capturing screenshots approximately every $interval_time seconds on $DEVICE_NAME - $DEVICE_SERIAL $(tput sgr 0)\n"
-printf "\n$(tput setaf 3)Setting a very low value might cause dropped frames or crash. Dont tell me that I did not warn you!$(tput sgr 0)\n"
-#Wait for adb device
-adb wait-for-device
 
-#Get device name
-DEVICE_NAME=$(adb shell getprop ro.product.model)
-DEVICE_SERIAL=$(adb shell getprop ro.serialno)
-#avoid edge cases for bandwidth and performance limit 4 screenshots every second
-# On avg on FHD device a png weighs 2.5MB = 10 MBps bandwidth + overhead so limit it to 4 screencaptures per second
 
-echo ++++++++++++++++++++++++++++++++++++++++++
-echo Press CTRL+C to stop.
-count=1
-while true
-do
+function main()
 {
-    echo "PATH:$FILE_PATH"
-    #Date stamp
-    DATE=`date +%Y-%m-%d:%H:%M:%S`
-    FILE_PATH=$SCREENSHOT_PATH
-    FILE_NAME=$DEVICE_NAME-$DATE-$count.png
-    adb exec-out screencap -p > "$FILE_PATH/$FILE_NAME";
-    printf "\n$(tput setaf 6)Captured Screenshot $count as: $(tput sgr 0)$FILE_NAME\n";
-    #sleep $1
-    if $COUNT_LIMIT_FLAG; then
-        {
-            if [[ $count -eq $COUNT_LIMIT ]]; then
-                printf "\n$(tput setaf 6)Saved total of $count Screenshots in "$FILE_PATH".$(tput sgr 0)\n";
-                exit 0;
-            fi;
-        }
-    fi
-    count=$((count+1));
-    sleep $interval_time;
-}
-done
+      #check if no args
+      if [ $# -eq 0 ]; then
+              printf "\n${BLUE}No arguments found. Using default values.${NC}\n"
+      fi;
+
+      # Process command line arguments.
+      while [ "$1" != "" ]; do
+          case ${1} in
+              -t | --time )           shift
+                                      interval_time=$1
+                                      ;;
+              -o | --output )         shift
+                                      SCREENSHOT_PATH=$1
+                                      ;;
+              -c | --count )          shift
+                                      COUNT_LIMIT_FLAG='true';
+                                      COUNT_LIMIT="$1"
+                                      ;;
+              -h | --help )           usage;
+                                      exit 0
+                                      ;;
+              -v | --version)         display_version;
+                                      exit 0
+                                      ;;
+              * )                     printf "\n${BLUE}Invalid argument(s). See usage below.${NC}\n"
+                                      usage;
+                                      exit 1
+                                      ;;
+          esac
+      	shift
+      done
+      screenshot_stream;
+  }
+main "$@"
diff --git a/stow/stow-all-files b/stow/stow-all-files
--- a/stow/stow-all-files
+++ b/stow/stow-all-files
@@ -1,5 +1,24 @@
 #!/usr/bin/env bash
 
+# This is a bash utility to help stow all th config files on your laptop neatly
+# Version:2.0
+# Author: Prasad Tengse
+# Licence: MIT
+# Github Repository: https://github.com/tprasadtp/minchu
+# Requirements - Bash v4.4 and above
+#              - GNU stow to be installed.
+
+#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Changelogs~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+# v0.0      - Initial placeholder script
+# v1.0      - Stowing files to directory
+# v1.1      - Seperate copy and stow operations (cant use cd in script)
+# v1.2      - Added ability to rename the old dotfiles directory.
+# v2.0      - Populate list to be stowed from a config file and then stow it.
+
+
+
+
+
 SCRIPT=`basename "$0"`
 YELLOW=$(tput setaf 3)
 BLUE=$(tput setaf 6)
@@ -19,6 +38,9 @@ Usage: ${YELLOW}${SCRIPT}${NC} [options]
 [-v --version]         [Display version info]
 [-h --help]            [Display this help message]
 This script's metadata Generated by ${gen_source} on ${gen_date}.
+This script uses a config file 'stow.list' containing list of directories to be stowed.
+If the $DOTFILE_DIR has been changed then you have to delete symlinks manually.
+If you want to stow other directories then just add them to the file with one directory per line.
 
 Notice any bugs? Please report it.
 You are welcome to create a pull request on Github, if you can make it better in any way!
@@ -57,14 +79,16 @@ function stow_files()
   line_fill;
   if command -v stow >&/dev/null; then
      if [ -d ${DOTFILE_DIR} ]; then
-      printf "Stowing files. By default .bashrc file stowed is in ${bashrc_dir}.\n"
+      printf "${BLUE}Stowing files.....\n"
       stow android-tools \
       neofetch \
       bash-${bashrc_dir}\
       image-processing \
       startup-items \
       dockerfiles\
-      git
+      git\
+      imwheel\
+      office-tools
       line_fill;
       return 0
     else
@@ -79,6 +103,52 @@ function stow_files()
   fi
 }
 
+
+function stow_files_withconfig()
+{
+  # Function to stow all valid files in directory
+  # Expects: Git repo to be copied and to be run from its current directory.
+  # Expects: GNU stow installed.
+  # Expects: afile named stow list containing all the directories to be stowed.
+  # Output: Stows the files in directory mentioned or default (Dotfiles)
+  if command -v stow >&/dev/null; then
+    #check if DOTFILE_DIR exists
+     if [ -d ${DOTFILE_DIR} ]; then
+      #check if config file with list of dir exists
+        if [ -e stow.list ]; then
+          printf "${BLUE}Stowing files.....${NC}\n"
+          line_fill;
+          while IFS= read line
+            do
+                 #read every line from file and stow it
+                 stow  $line;
+                  if [ "$?" = "0" ]; then
+                     printf "Stowed:${line}\n"
+                  else
+                      printf "Some error occured during adding  ${line}, Ignoring and moving on!\n"
+                  fi
+            done < stow.list
+            line_fill;
+          return 0;
+        else
+          printf "Config file stow.list is missing\n"
+          line_fill;
+          exit 1;
+        fi
+    else
+      printf "\n${DOTFILE_DIR} is not present under ${HOME}\n"
+      line_fill;
+      return 1;
+    fi
+  else
+    printf "\nProgram stow is not installed. Please install stow.\n";
+    line_fill;
+    return 1;
+  fi
+}
+
+
+
 function main()
 {
       #check if no args
@@ -91,7 +161,7 @@ function main()
       # Process command line arguments.
       while [ "$1" != "" ]; do
           case ${1} in
-              -s | --stow )           stow_files;
+              -s | --stow )           stow_files_withconfig;
                                       exit $?;
                                       ;;
               -v | --version)         display_version;
